#!/bin/sh

if [[ $1 == install || $1 == upgrade ]]; then
	if [ -f /var/mobile/Library/Preferences/com.eswick.harbor.license ]; then
		echo Removing license...
		rm -f /var/mobile/Library/Preferences/com.eswick.harbor.license
	fi
fi